services:
  latex:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WATCHEXEC_ARCH_NAME: ${WATCHEXEC_ARCH_NAME}
        WATCHEXEC_VERSION: ${WATCHEXEC_VERSION}
    volumes:
      - ./src:/latex/src           # sources
      - ./dist:/latex/dist         # target for PDF files
    tty: true
    stdin_open: true
    